### PR TITLE
Add newline after PHP opening tags.

### PR DESCRIPTION
**Pull request by mtricht**
This went wrong when using the --remove-top-comment option, resulting in `<?phpnamespace`.

### CODE REVIEW

**Comment by mtricht** [comment]
I see that the test is failing because it's asserting for `<?phpfoo`.
@onema Is this really intentional behavior?

**Comment by onema** [comment]
Not intended behavior, that was an oversight.

If you update [line 33](https://github.com/onema/classyfile/blob/master/tests/BasicClassTemplateTest.php#L33) in the `BasicClassTemplateTest.php` file with the following line:

``` php
$expectedTemplate = sprintf('<?php%s%s%s%s%s%s%s%s%s', PHP_EOL, 'foo', PHP_EOL, 'bar', PHP_EOL, 'blah', PHP_EOL, 'lala', PHP_EOL);
```

This will be the intended behavior, and the test will pass. I'll make sure to merge the pull request after that.

Good catch by the way!

**Comment by onema** [comment]
I fixed this in PR #20

**Comment by mtricht** [comment]
Awesome! :)

**Pull request closed without merging**
